import argparse


def main():
    parser = argparse.ArgumentParser(description="Generate a greeting from Codex")
    parser.add_argument("name", help="Name to greet")
    parser.add_argument("--output", "-o", default="greeting.txt", help="Output file")
    args = parser.parse_args()

    greeting = f"Hello, {args.name}! This file was generated by Codex."
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(greeting + "\n")
    print(f"Greeting written to {args.output}")


if __name__ == "__main__":
    main()
